name: CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'

      - name: Compile Haskell to Wasm
        run: docker run --rm -v $(pwd):/project -w /project terrorjack/asterius ahc-link --input-hs src/JsExports.hs --output-prefix js-exports --no-main --browser --export-function parseSrc

      - name: Build frontent
        run: |
          cd site
          npm ci
          npm run build
          cp ../src/js-exports.wasm ./dist/

      - name: Deploy
        run: node_modules/.bin/gh-pages -d dist --user "Nikita Kirsanov <kitos.kirsanov@gmail.com>" --repo https://${{ secrets.GH_TOKEN }}@github.com/kitos/habel.git
